// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIpeV5MlHn9nMdce2PdFrBf0K5L228Cuw',
    appId: '1:109604143270:web:4e10414501b9bb17733467',
    messagingSenderId: '109604143270',
    projectId: 'benji-f81a0',
    authDomain: 'benji-f81a0.firebaseapp.com',
    storageBucket: 'benji-f81a0.firebasestorage.app',
    measurementId: 'G-6FZHTNQM55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ZNX9Bz94SyhX_mHZZUezNPuBVhk3-60',
    appId: '1:109604143270:android:be04dc5d59e0ad99733467',
    messagingSenderId: '109604143270',
    projectId: 'benji-f81a0',
    storageBucket: 'benji-f81a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhTJQ1N0NYqu5x_uoboxd3PMuFjhdW_DI',
    appId: '1:109604143270:ios:3d69ea11267844f1733467',
    messagingSenderId: '109604143270',
    projectId: 'benji-f81a0',
    storageBucket: 'benji-f81a0.firebasestorage.app',
    iosBundleId: 'com.benjamin.prochat',
  );
}
